---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: babylon-catalog-api
  labels:
    {{- include "babylon.labels" $ | nindent 4 }}
    app.kubernetes.io/component: catalog-api
rules:
- apiGroups:
  - babylon.gpte.redhat.com
  resources:
  - catalogitems
  verbs:
  - get
  - list
  - watch
